### PR TITLE
Resizing now obeys preventCollision restrictions

### LINKED ISSUE #1933: preventCollision not taking effect while resizing items
### Describe the bug

After 1.4.0 version, preventCollision appears to be being ignored when resizing items.

### Your Example Website or App

https://codesandbox.io/s/elated-napier-gr5lgl

### Steps to Reproduce the Bug or Issue

1. Change Compaction Type to No Compaction
2. Use resize handle in horizontal (element itself will be pushed down until find some free space)
3. Use resize handle in vertical (elements bellow will be pushed)

### Expected behavior

When resizing with preventCollision, I expect the element to just fill the free space when available without moving out of place and not pushing the other elements, exactly the same way as in version 1.3.4

### react-grid-layout library version

1.4.1

### Operating System Version

Linux

### Browser

Chrome

### Additional context

_No response_

### Screenshots or Videos

_No response_

### PR DESCRIPTION
**Pull request by dseif**
## Description

This PR fixes #1933 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

This bug was introduced as part of the work in #1917 because `preventCollision` wasn't taken into account when performing resizes.

## Mobile & Desktop Screenshots/Recordings
Both examples have `preventCollision=true` and `compactType=null` as was defined in #1933.

### Before
https://github.com/react-grid-layout/react-grid-layout/assets/580086/2f24816d-68ff-488e-ad1c-c4e2b0f9af8e

### After
https://github.com/react-grid-layout/react-grid-layout/assets/580086/12dd558f-8af3-4a7d-9ca1-4559fde81da9

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 examples
- [x] 🙅 no documentation needed

### CODE REVIEW

File: lib/ReactGridLayout.jsx [hunk 1]
```diff
@@ -429,31 +461,17 @@ export default class ReactGridLayout extends React.Component<Props, State> {
...
+      l.w = w;
+      l.h = h;
 
       return l;
     });
 
     // Shouldn't ever happen, but typechecking makes it necessary
     if (!l) return;
 
-    let finalLayout;
```
Comment (dseif) [inline lib/ReactGridLayout.jsx:439]: I moved the majority of this logic to within `withLayoutItem`. This probably should have been within there to begin with, so sorry about missing that originally.

File: lib/ReactGridLayout.jsx [hunk 2]
```diff
@@ -429,31 +461,17 @@ export default class ReactGridLayout extends React.Component<Props, State> {
...
-      if (["ne", "n", "nw"].indexOf(handle) !== -1) {
-        y = l.y + (l.h - h);
-        h = l.y !== y && y < 0 ? l.h : h;
-        y = y < 0 ? 0 : y;
-      }
-
-      l.w = w;
-      l.h = h;
+    finalLayout = newLayout;
+    if (shouldMoveItem) {
```
Comment (dseif) [inline lib/ReactGridLayout.jsx:474]: Similarily, we can't move the item within `withLayoutItem` which is why this is done outside of that block since we need the resulting `Layout` to perform the operation.

File: lib/ReactGridLayout.jsx [hunk 3]
```diff
@@ -405,18 +405,50 @@ export default class ReactGridLayout extends React.Component<Props, State> {
...
+        }).filter(layoutItem => layoutItem.i !== l.i);
         hasCollisions = collisions.length > 0;
 
         // If we're colliding, we need adjust the placeholder.
         if (hasCollisions) {
+          // Reset layoutItem dimensions if there were collisions
+          y = l.y;
+          h = l.h;
+          x = l.x;
+          w = l.w;
```
Comment (dseif) [inline lib/ReactGridLayout.jsx:451]: This is the core of the change. If we detect that there was a collision *and* `preventCollision` is enabled, we reset the w/h/x/y values of the LayoutItem.

**Comment by dseif** [comment]
To pass CI linter task, this will depend on #1938 being merged. Opted to fix those issues there instead of muddying this PR with that noise.

**Comment by dseif** [comment]
@STRML if you have time this week would be great to get your eyes on this and #1938

**Comment by STRML** [comment]
Thanks, I'll review this shortly. Please rebase on master.

File: lib/ReactGridLayout.jsx [hunk 4]
```diff
@@ -429,31 +461,17 @@ export default class ReactGridLayout extends React.Component<Props, State> {
           if (Number.isFinite(leastY)) l.h = leastY - l.y;
         }
       }
+      l.w = w;
```
Comment (STRML) [inline lib/ReactGridLayout.jsx:464]: Doesn't this make L452-L461 essentially dead code?

File: test/spec/lifecycle-test.js [hunk 5]
```diff
@@ -881,6 +881,24 @@ describe("Lifecycle tests", function () {
           });
         });
       });
+
+      it("Does not cause elements to move when resizing with preventCollision=true and no compaction (#1933)", () => {
```
Comment (STRML) [inline test/spec/lifecycle-test.js:885]: Worth having a test where you can resize it (there's some empty space), as well as where you can resize it 1 grid unit but, say, not 2, because an item is in the way.

**Review by STRML — CHANGES_REQUESTED** [review]
Minor comment & question

File: lib/ReactGridLayout.jsx (hunk 4 above)
Comment (dseif) [reply lib/ReactGridLayout.jsx:464]: Yes, thanks for catching. 452-461 _shouldn't_ be needed anymore after testing, looks like the boundaries are still being calculated correctly.

File: test/spec/lifecycle-test.js (hunk 5 above)
Comment (dseif) [reply test/spec/lifecycle-test.js:885]: Sounds good, happy to add those cases as well.

File: test/spec/lifecycle-test.js [hunk 6]
```diff
@@ -881,6 +881,100 @@ describe("Lifecycle tests", function () {
...
+          const gridLayout = wrapper.find("ReactGridLayout");
+          const itemId = 0;
+          const gridItem0 = findGridItemByText(gridLayout, itemId);
+          const handleElement = findHandleForGridItem(gridItem0, "e");
+          const pos = getCurrentPosition(gridItem0);
+          const positionBeforeResize = getGridItemData(gridLayout, itemId);
+
+          // Resize right two columns
+          resizeTo(handleElement, true, pos, pos.left + colWidth, pos.top);
+          resizeTo(handleElement, false, pos, pos.left + colWidth * 2, pos.top);
```
Comment (dseif) [inline test/spec/lifecycle-test.js:943]: This duplication of `resizeTo` calls here is intentional. We first move 1 column over (which is valid, no collisions), then we move another column over (which is invalid, there is collisions). This is to better simulate an actual drag.

The problem was with the collision detection and the logic that's in place is that if we went immediately from currentX/currentY -> newX/newY without any valid positions inbetween, the "last known good X/Y are the original position. This isn't realistic behaviour when a user actually drags their mouse, which is why I simulated it like this.

A better solution is probably to look into using `DragEvent` instead of `MouseEvent` for these simulations. I can take a look into that outside of this PR to have tests better simulate reality.

**Review by STRML — APPROVED** [review]

File: lib/ReactGridLayout.jsx [hunk 7]
```diff
@@ -405,55 +405,64 @@ export default class ReactGridLayout extends React.Component<Props, State> {
...
-            if (layoutItem.y > l.y) leastY = Math.min(leastY, layoutItem.y);
-          });
-
-          if (Number.isFinite(leastX)) l.w = leastX - l.x;
-          if (Number.isFinite(leastY)) l.h = leastY - l.y;
+          // Reset layoutItem dimensions if there were collisions
+          y = l.y;
+          h = l.h;
+          x = l.x;
+          w = l.w;
```
Comment (STRML) [inline lib/ReactGridLayout.jsx:451]:
```suggestion
          w = l.w;
          shouldMoveItem = false;
```

Should this not be done to short-circuit the move, since we know it's not happening?

Comment (dseif) [reply lib/ReactGridLayout.jsx:451]: Yea good suggestion, updated.

**Comment by STRML** [comment]
Published in `1.4.2`
